# ---------------------------------------------------------
# CẤU HÌNH MẠNG CHO HỆ THỐNG ĐẤU GIÁ (ONLINE AUCTION SYSTEM)
# ---------------------------------------------------------

# Địa chỉ IP công cộng (Public IP) của máy chủ Azure VM
server.host=20.189.123.212

# Cổng dịch vụ TCP Socket đấu giá (phía Server lắng nghe trên 8080)
server.port=8080

# Cổng dịch vụ HTTP tải ảnh sản phẩm (phía Server lắng nghe trên 9090)
image.server.port=9090
